### PR TITLE
Add user object to request after decoding token. (flask & falcon)

### PR DESCRIPTION
**Pull request by alexanderson**
@artsalliancemedia/thunderstorm 

Instead of giving the raw decoded token to the framework (flask `g` or falcon `req.context`) we now build a `User` object.

Sorry @will-norris I had to move some of these fixtures back around.
Framework specific tests and fixtures go into a dedicated dir. Agnostic ones moved back to conftest as they don't belong in the library module.

### CODE REVIEW

**Comment by will-norris** [comment]
Ah yeah I dont really have any strong feelings on this :) I just moved stuff around before to make the structure more like what I'm used to on the services but I think in this case where we're supporting multiple frameworks this your structure more sense. Not too sure about moving the generate_private_key and encode_token functions to a utils module though since they were only intended to be used by the test fixtures. I think it would make more sense to keep them in the same modules as the fixtures that use them.

**Comment by robyoung** [comment]
@will-norris I think the reason for the `generate_private_key` and `encode_token` functions into utils was so that the services could make use of it in their tests. So we'd need another way of solving that.

**Comment by robyoung** [comment]
I agree do agree that it should be made more clear what it's supposed to be used for.

**Comment by will-norris** [comment]
yeah that was my main concern, once it was moved into a test directory I was happy with it :+1:

**Comment by alexanderson** [comment]
yeah I've noticed this, looking into it.

**Comment by alexanderson** [comment]
TODO: I'm seeing repetition across services with fixtures. Could make a new repo which adds these fixtures into the default set via a pytest extension.

**Comment by robyoung** [comment]
... or, you know, just include a module that has the fixtures in it :trollface:

**Comment by robyoung** [comment]
or, less trolly, change the `testing` module so that it just implements the contents of all the fixtures as plain old functions and then the only duplication in the services is wrapping the the ones they need as fixtures. That way you centralise the logic without having fixtures magically appearing in services without people specifically asking for them.

**Comment by robyoung** [comment]
hang on, you've already pretty much done it

**Pull request merged**
