### PR TITLE
[fix] @signals.worker_ready.connect does not work inside of a function

### PR DESCRIPTION
**Pull request by will-norris**
@artsalliancemedia/thunderstorm

## Description - This PR:
Adds `weak=True` to `@signals.worker_ready.connect` to fix some issues we were having
Fixes some tests which were missing some params in their calls to one of the Session class constructors
Manually specifies the key order to use in the composite primary key of the RolePermissionAssociationMixin. Not sure if this was to do with the use of `@declared_attr` or just a quirk of sqlalchemy but when creating composite primary keys using sqlalchemy the key order could randomly change between test runs. e.g. given a composite PK called my_key composed of the fields a and b the key would sometimes be (a, b) and other times (b, a).

### CODE REVIEW

**Comment by swoiow** [comment]
@will-norris hi, William, just a tech discuss.

the first time i bring signal define in the top level, in that time time, to wrote those modify is because i think the signal need to be create before celery instance init. But last night i review the signal part of celery, maybe my first opinion is not right.

``` playground.py

from celery import Celery
app = Celery('tasks', broker='redis://localhost:6379/0')

import logging
from celery import signals

logger = logging.getLogger()

@signals.worker_ready.connect
def do_ready(sender, **kwargs):
    logger.error("uh, this is root level")
    if 'ts_auth.permissions.sync' in sender.app.tasks:
        sender.app.tasks['ts_auth.permissions.sync'].delay()
```

Actually, the over code, although define the signal after celery instance, the signal still will run.

so whats the key point of this question, 
in the celery source code, `https://github.com/artsalliancemedia/thunderstorm-auth-library/pull/80`
`signals.worker_ready.connect` has a params -- retry, tell me answer, **weak references**.

keep the origin write, and just modify `@signals.worker_ready.connect` => `@signals.worker_ready.connect(weak=False)`, the problem is solved.

---
more things, and why define signal in the top level will work, i think maybe in this situation the function `do_ready` is a strong references now.

---
So both  PR80(this pr) and PR81, can fix the signal problem.

**Comment by shipperizer** [comment]
@will-norris just to explain better, i had a chat with @swoiow and he said that by just adding `weak=False` will make it work in a mroe elegant way, see  #81 

Maybe we should use that, as it's more "elegant", still is a bit of magic

**Comment by will-norris** [comment]
> @will-norris just to explain better, i had a chat with @swoiow and he said that by just adding `weak=False` will make it work in a mroe elegant way, see #81

Sounds good to me, I've pulled his changes into this PR so we can just roll them out along with the fixes for the tests that I have done. No sense in having a standalone PR for a one line change when it can be avoided

**Comment by shipperizer** [comment]
like @mafrosis would say: cool bro

**Comment by will-norris** [comment]
Your solution looks much better, cheers :+1:

**Pull request merged**
